### ISSUE TITLE
Not working after update, more errors after reinstall

### ISSUE THREAD

**Issue by Stooovie** [KlipperScreen/KlipperScreen#1099]
### What happened?

Discord link says "invalid invite", asking here.

After update, KS stopped displaying (only see blue screen with "Launch these commands on your Linux PC"). Manual reinstall gave me these:
![Screenshot 2023-08-24 at 12 47 15](https://github.com/KlipperScreen/KlipperScreen/assets/10572373/0d1b4fd2-9e4b-44e4-be00-1cabf6127d20)
Uninstall/reinstall with KIAH does the same thing.

This is a very standard install - Raspbian on RPi3, installed via KIAUH. Been working as expected for almost a year. No HW change, no SW change done by me - only updates via moonraker.

Any tips? Thanks.

### What did you expect to happen instead?

KS to continue working

### How to reproduce this bug?

reinstall KS manually or via KIAUH

### Log output

```shell
Log:

https://nc.jirifiala.cz/s/KS97GpZbK9iijg9
```

**Comment by alfrix** [comment]
the warnings are because of a wrong path in [update_manager] see #1100 

in short just change this line in moonraker.conf from:
`virtualenv: ~/.KlipperScreen-env/bin/python`
to
`virtualenv: ~/.KlipperScreen-env`

the rest of the log indicates that klipperscreen is starting up correctly, the issue must be in the network or the launch script configuration, or maybe the phone itself, but  not in klipperscreen, if you can't make it work with the XSDL method you may be able to make it work with the VNC method:
https://klipperscreen.readthedocs.io/en/latest/VNC/
