### ISSUE TITLE
[FR] Screen loads slowly when booting

### ISSUE THREAD

**Issue by MINGDA3D** [KlipperScreen/KlipperScreen#1140]
### Requested feature

The mainboard of the host computer I use is BIGTREETECH CB1 and the screen is BTT TFT70. Every time I turn on the computer, the screen will go black for 7 or 8 seconds. The screen booted up white and then faded to black, never showing anything else, no splash screen or boot text either. Is there any way to make the screen display thesplash screen as soon as possible instead of going black?

**Comment by alfrix** [comment]
there are ways to show videos on startup like: https://www.youtube.com/watch?v=Y1NXYyBIs9A&t=14s&pp=ygUVa2xpcHBlcnNjcmVlbiBzdGFydHVw
and other methods generic to linux like showing text output during boot, etc

Closing since it's not a valid feature of Klipperscreen, these are things that should be done in the Host OS
