### ISSUE TITLE
[FR] Webcam rotation

### ISSUE THREAD

**Issue by R4toLoko** [KlipperScreen/KlipperScreen#976]
I have the webcam working just fine like so:

```
[printer Trident]
camera_url: http://127.0.0.1/webcam/?action=stream
```
I keep hitting the webcam for some magic reason, so seeing the feed right on the display without having to grab my phone or PC to make sure the timelapse will be fine, is a must.
Although I can see the webcam, it is upside down and there nothing within the documentation that mention anything about how to rotate it, etc.

Mainsail does allow you to rotate and flip but there is nothing for the KlipperScreen itself.

Thank you

**Comment by mpaw** [comment]
@R4toLoko If you're using crowsnest you can rotate the camera by updating either the [custom_flags](https://crowsnest.mainsail.xyz/configuration/cam-section#custom_flags) or [v4l2ctl](https://crowsnest.mainsail.xyz/configuration/cam-section#v4l2ctl) config. Since this will make the change to the stream itself, everything that views the stream (mainsail, klipperscreen, etc...)
